services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - '8761:8761'
    environment:
      SERVER_PORT: '8761'
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - '8081:8081'
    environment:
      SERVER_PORT: '8081'
      SPRING_APPLICATION_JSON: >-
        {"eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/",
         "spring.rabbitmq.host":"rabbitmq",
         "spring.rabbitmq.port":5672,
         "spring.rabbitmq.username":"guest",
         "spring.rabbitmq.password":"guest"}
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - backend

  payments-service:
    build:
      context: ./payments-service
    container_name: payments-service
    ports:
      - '8083:8083'
    environment:
      SERVER_PORT: '8083'
      SPRING_APPLICATION_JSON: >-
        {"eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/",
         "spring.rabbitmq.host":"rabbitmq",
         "spring.rabbitmq.port":5672,
         "spring.rabbitmq.username":"guest",
         "spring.rabbitmq.password":"guest"}
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - backend

  orders-service:
    build:
      context: ./orders-service
    container_name: orders-service
    ports:
      - '8084:8084'
    environment:
      SERVER_PORT: '8084'
      SPRING_APPLICATION_JSON: >-
        {"eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/",
         "spring.rabbitmq.host":"rabbitmq",
         "spring.rabbitmq.port":5672,
         "spring.rabbitmq.username":"guest",
         "spring.rabbitmq.password":"guest"}
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - backend

  my-api-gateway:
    build:
      context: ./my-api-gateway
    container_name: my-api-gateway
    ports:
      - '8082:8082'
    environment:
      SERVER_PORT: '8082'
      SPRING_APPLICATION_JSON: >-
        {"eureka.client.service-url.defaultZone":"http://eureka-server:8761/eureka/",
         "spring.rabbitmq.host":"rabbitmq",
         "spring.rabbitmq.port":5672,
         "spring.rabbitmq.username":"guest",
         "spring.rabbitmq.password":"guest"}
    depends_on:
      - eureka-server
      - api-gateway
      - payments-service
      - orders-service
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge
